biclo_oauth2_server_default_api:
    pattern: /api
    defaults: { _controller: "BicloOAuth2ServerBundle:Default:api" }

biclo_oauth2_server_default_links:
    pattern: /links
    defaults: { _controller: "BicloOAuth2ServerBundle:Default:links" }

biclo_oauth2_server_default_create_client:
    pattern: /links/createClient
    defaults: { _controller: "BicloOAuth2ServerBundle:Default:createClient" }

biclo_oauth2_server_security_login:
    pattern: /oauth/v2/auth_login
    defaults: { _controller: "BicloOAuth2ServerBundle:Security:login" }

biclo_oauth2_server_security_login_check:
    pattern: /oauth/v2/auth_login_check
    defaults: { _controller: "BicloOAuth2ServerBundle:Security:loginCheck" }
