didier_oauth2_server_client:
  resource: "@DidierOAuth2ServerBundle/Controller/ClientController.php"
  type: annotation

didier_oauth2_server_default_user:
    pattern: /api/me
    defaults: { _controller: "DidierOAuth2ServerBundle:Default:user" }

didier_oauth2_server_default_links:
    pattern: /links
    defaults: { _controller: "DidierOAuth2ServerBundle:Default:links" }

didier_oauth2_server_default_create_client:
    pattern: /links/createClient
    defaults: { _controller: "DidierOAuth2ServerBundle:Default:createClient" }

didier_oauth2_server_security_login:
    pattern: /oauth/v2/auth_login
    defaults: { _controller: "DidierOAuth2ServerBundle:Security:login" }

didier_oauth2_server_security_login_check:
    pattern: /oauth/v2/auth_login_check
    defaults: { _controller: "DidierOAuth2ServerBundle:Security:loginCheck" }

didier_oauth2_server_security_register:
    pattern: /oauth/v2/register
    defaults: { _controller: "DidierOAuth2ServerBundle:Security:register" }

didier_oauth2_server_security_revoke:
    pattern: /oauth/v2/revoke
    defaults: { _controller: "DidierOAuth2ServerBundle:Security:revoke" }
