fos_oauth_server_token:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"

fos_oauth_server_authorize:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/authorize.xml"

didier_oauth2_server_default_user:
    pattern: /api/me
    defaults: { _controller: "DidierOAuth2ServerBundle:Default:user" }
