imports:
    - { resource: parameters_dist.yml }
    - { resource: parameters.yml, ignore_errors: true }
    - { resource: security.yml }

framework:
    secret: %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale: "%locale%"
    translator: { fallback: %locale% }
    trusted_proxies: ~
    session: ~
    fragments: ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    bundles:        [ ]
    filters:
        cssrewrite: ~

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        entity_managers:
            default:
                mappings:
                    BicloOAuth2ServerBundle: ~
                    BicloUserBundle: ~

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%
    spool:     { type: memory }

fos_oauth_server:
    db_driver: orm       # Driver availables: orm, mongodb, or propel
    client_class:        Biclo\Bundle\OAuth2ServerBundle\Entity\Client
    access_token_class:  Biclo\Bundle\OAuth2ServerBundle\Entity\AccessToken
    refresh_token_class: Biclo\Bundle\OAuth2ServerBundle\Entity\RefreshToken
    auth_code_class:     Biclo\Bundle\OAuth2ServerBundle\Entity\AuthCode
