_didier_crud:
    resource: "@DidierCRUDBundle/Resources/config/routing.yml"
    prefix: /crud

_biclo_oauth_2_server:
    resource: "@DidierOAuth2ServerBundle/Resources/config/routing.yml"

_didier_user:
    resource: "@DidierUserBundle/Resources/config/routing.yml"

_didier_website:
    resource: "@DidierWebsiteBundle/Resources/config/routing.yml"

didier_website_login:
    pattern: /login

didier_website_logout:
    pattern: /logout
