fos_oauth_server_token:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"

fos_oauth_server_authorize:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/authorize.xml"

biclo_oauth_2_server:
    resource: "@BicloOAuth2ServerBundle/Resources/config/routing.yml"
