security:
    encoders:
        Didier\Bundle\UserBundle\Entity\User:
            algorithm:        sha512
            encode-as-base64: true
            iterations:       5

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN]

    providers:
        biclo_user:
            entity:
                class: Didier\Bundle\UserBundle\Entity\User
                property: email

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        oauth_token:
            pattern:  ^/oauth/v2/token
            security: false

        api:
            pattern:   ^/api
            fos_oauth: true
            stateless: true

        website:
            pattern:    ^/
            form_login:
                provider:   biclo_user
                login_path: didier_website_login
                check_path: /login-check
            anonymous: true
            logout:
                path: didier_website_logout

    access_control:
        # - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        # - { path: ^/, roles: IS_AUTHENTICATED_FULLY }
        # - { path: ^/oauth/v2/auth, roles: IS_AUTHENTICATED_FULLY }
