security:
    encoders:
        Biclo\Bundle\UserBundle\Entity\User:
            algorithm:        sha512
            encode-as-base64: true
            iterations:       5

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        biclo_user:
            entity: { class: Biclo\Bundle\UserBundle\Entity\User, property: email }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        oauth_token:
            pattern:    ^/oauth/v2/token
            security:   false

        api:
            pattern: ^/api
            fos_oauth: true
            stateless: true

        oauth_authorize:
            pattern:    ^/oauth/v2/auth
            form_login:
                provider: biclo_user
                check_path: /oauth/v2/auth_login_check
                login_path: /oauth/v2/auth_login
            anonymous: true

    access_control:
        - { path: ^/oauth/v2/auth_login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/oauth/v2/auth, roles: IS_AUTHENTICATED_FULLY }
